### ISSUE TITLE
project demo?

### ISSUE THREAD

**Issue by rawformula** [hairibar/Hairibar.Ragdoll#1]
hi, this looks like a very interesting project.

could you upload a set-up, working demo, I mean package? there's mixamo's distributable beta character you can use. 

thanks

**Comment by hairibar** [comment]
Sure!
I haven't put up a demo project because I don't know if I'm allowed to redistribute a model from the asset store. Could you link me to mixamo's distributable character? I'm googling for it but everything I find is about the animation licensing, nothing about models.

**Comment by rawformula** [comment]
great.
you can find mixamo's characters all around in projects on github. (you cannot distribute a model from the assetstore)
but if you want to be perfectly sure, you can use my character I made with makehuman
http://www.mediafire.com/file/kzkg27dm9ea4n9y/man01.zip/file

**Comment by rawformula** [comment]
hi, is it coming along?

if you're short on time, maybe just the screenshots of the inspector (how things are set up) would help.

**Comment by hairibar** [comment]
Hi! Yeah sorry, a couple of deadlines bunched up on me so I'm pretty busy right now. I reckon I'll get the time next week. In the meantime, [here's a writeup](https://www.aitor-iribar.dev/physics-driven-animation) I did a while ago.

**Comment by hairibar** [comment]
Hi! Just letting you know that I finally put together a bunch of demo scenes. As of v1.2.0, they're bundled with the package as samples; so you just have to press the import button in the package manager. 

I'll be writing a small manual on the readme in the coming days as well.
