### ISSUE TITLE
Cannot get it to import.

### ISSUE THREAD

**Issue by SubStoned** [hairibar/Hairibar.Ragdoll#3]
I've been trying for the whole evening now, but I cannot get it to import. I keep getting the invalid dependencies error in Unity.
I've tried importing the json file, modifying it as said in the readme and also tried importing straight from git yet no luck.
From what I can tell it seems to be a problem with the NaughtyAttributes.

**Comment by hairibar** [comment]
That's odd, I've tried it on a fresh project and it worked.
When you say "importing the json file", what do you mean exactly? In case the documentation is confusing about this, you're supposed to add those lines to your project's manifest.json.

If that is what you're doing, could show me the exact error message? That might help diagnose the issue.

**Comment by repasDev** [comment]
Oh crud, didn't realize you're supposed to add it to the project. Thanks for the help and great project man!
